name: Build Essential Platforms (Windows + macOS)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.15'
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload Windows VST3
      uses: actions/upload-artifact@v4
      with:
        name: SimpleLowPass-Windows-VST3
        path: build/SimpleLowPassPlugin_artefacts/VST3/SimpleLowPass.vst3

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.15'
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload macOS AU
      uses: actions/upload-artifact@v4
      with:
        name: SimpleLowPass-macOS-AU
        path: build/SimpleLowPassPlugin_artefacts/AU/SimpleLowPass.component
    
    - name: Upload macOS VST3
      uses: actions/upload-artifact@v4
      with:
        name: SimpleLowPass-macOS-VST3
        path: build/SimpleLowPassPlugin_artefacts/VST3/SimpleLowPass.vst3 